[tool.poetry]
name = "flypper"
version = "0.1.0"
description = ""
authors = ["Nicolas Zermati <nicoolas25@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Werkzeug = "^2.0.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.910"
Werkzeug = "^2.0.2"
Jinja2 = "^3.0.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
